---
title: "CMDA-4654  \n Group Exercise 1B"
author: "Sophia Gavasheli and Jacob Carlson"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  pdf_document:
    highlight: kate
keep_tex: no
number_sections: no
html_document:
  df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---
  

```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

library(knitr) # I recommend doing this here

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA, # Recommended
                      fig.path = "./figures1B/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE, # Turn off warnings
                      R.options = list(width = 100))

library(here)
setwd(here()) # sets path to root of RProject

```

\clearpage



# 1. Reintroduction
Can we predict a team's seasonal runs based on it's offensive stats(KNN Regression)

Can we predict a players position based on their offensive stats(KNN Classification and Naive Bayes)

```{r}
pos     <- read.csv("Fielding.csv")
batting <- read.csv("batting.csv")

# Getting highest position played for players
primary_pos <- pos %>%
  group_by(playerID, yearID, POS) %>%
  summarise(G = sum(G), .groups = "drop") %>%
  group_by(playerID, yearID) %>%
  slice_max(G, n = 1, with_ties = FALSE) %>%
  select(playerID, yearID, POS)

# Merge Position into Player and Year to condense data
stats <- merge(batting, primary_pos,
               by = c("playerID", "yearID"), all.x = TRUE)

# Keeps only American and National League
stats_clean <- stats[stats$lgID %in% c("AL", "NL"), ]
stats_clean <- stats_clean[!is.na(stats_clean$POS), ]


#####################################################
####### REGRESSION !!!!!!!!!
## Seperates by team for regression prediction. 
by_team <- aggregate(cbind(AB, R, H, HR, SB, BB, SO) ~ teamID + yearID,
                     data = stats_clean, FUN = sum)


# Creates second frame to scale data per at-bat
by_team_scaled <- by_team

by_team_scaled$H  <- by_team$H  / by_team$AB
by_team_scaled$HR <- by_team$HR / by_team$AB
by_team_scaled$BB <- by_team$BB / by_team$AB
by_team_scaled$SB <- by_team$SB / by_team$AB
by_team_scaled$SO <- by_team$SO / by_team$AB
by_team_scaled$BA <- by_team$H  / by_team$AB


###################################################

# CLASSIFICATION AND BAYES!!!!!!!!!!!!!
# Uses 100 minimum at bats to remove extreme cases
pos_data <- stats_clean[stats_clean$AB >= 100, ]

# Changes The infield positions into a common infield tab
for(i in 1:length(pos_data$POS)){
  if(pos_data$POS[i] == "1B" || 
     pos_data$POS[i] == "2B" ||
     pos_data$POS[i] == "3B" ||
     pos_data$POS[i] == "SS" ){
    pos_data$POS[i] = "IF"
  }
}
position_names <- c(
  "IF" = "Infield",
  "C"  = "Catcher",
  "OF" = "Outfield",
  "P"  = "Pitcher"
)
pos_data$Position <- factor(position_names[pos_data$POS])


pos_data <- pos_data[, c("playerID", "yearID", "Position",
                         "H", "HR", "BB", "SO", "SB", "AB")]

pos_data_scaled <- pos_data

pos_data_scaled$BA <- pos_data$H  / pos_data$AB
pos_data_scaled$HR <- pos_data$HR / pos_data$AB
pos_data_scaled$BB <- pos_data$BB / pos_data$AB
pos_data_scaled$SO <- pos_data$SO / pos_data$AB
pos_data_scaled$SB <- pos_data$SB / pos_data$AB

pos_data_scaled$Position <- factor(position_names[pos_data$POS])

pos_data_scaled <- pos_data_scaled[, c("playerID", "yearID", "Position",
                                  "BA", "HRA", "BBA", "SOA", "SBA")]
```



```{r}


```


